controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_exercises:
    path: /exercises/search
    controller: App\Controller\ExerciceController::search
    methods: GET
